In [1]:
from sklearn.linear_model import LinearRegression
import pandas as pd

In [2]:
df = pd.read_csv('IceCreamData.csv')

In [3]:
df

Temperature     Revenue
0      24.566884  534.799028
1      26.005191  625.190122
2      27.790554  660.632289
3      20.595335  487.706960
4      11.503498  316.240194
..           ...         ...
495    22.274899  524.746364
496    32.893092  755.818399
497    12.588157  306.090719
498    22.362402  566.217304
499    28.957736  655.660388

[500 rows x 2 columns]

In [4]:
lr = LinearRegression()

In [5]:
x = df.iloc[:,0].values.reshape(-1,1)
y= df.iloc[:,1].values.reshape(-1,1)

In [6]:
from sklearn.model_selection import train_test_split

In [7]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=0)

In [8]:
x_test.shape

(100, 1)

In [9]:
lr.fit(x_train,y_train)

LinearRegression()

In [10]:
lr.coef_

array([[21.5133908]])

In [11]:
lr.intercept_

array([43.73357869])

In [12]:
from sklearn.linear_model import LinearRegression

In [13]:
sklr = LinearRegression()

In [14]:
sklr.fit(x_train,y_train)

LinearRegression()

In [15]:
sklr.coef_

array([[21.5133908]])

In [16]:
sklr.intercept_

array([43.73357869])

In [17]:
y_hat =lr.predict(x_test)

In [26]:
from sklearn.metrics import mean_absolute_error

In [27]:
mean_absolute_error(y_test,y_hat)

18.303213530102894

In [28]:
from sklearn.metrics import mean_absolute_error,mean_squared_error

In [29]:
mse = mean_squared_error(y_test, y_hat)
mse

528.2150684519339

In [30]:
import numpy as np

In [31]:
np.sqrt(mse)

22.982929936192512

In [32]:
from sklearn.metrics import mean_absolute_error,r2_score

In [33]:
R_2 = r2_score(y_test,y_hat)
R_2

0.9837324255882576